config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 設定首頁
  root "blog/posts#index"
  # 設定功能路由
  scope module: "blog" do
    resources :posts
    get "about" => "pages#about", as: :about
    get "contact" => "pages#contact", as: :contact
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	# FriendlyId Gem 的必備程式碼
  extend FriendlyId
  friendly_id :title, use: :slugged

  # 首頁 Post，按照 新 -> 舊
  scope :most_recent, -> { order(id: :desc) }

  # 上傳照片
  mount_uploader :image, PhotoUploader

	def should_generate_new_friendly_id?
		title_changed?
	end

end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController

    def about
    end

    def contact
    end

  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.most_recent
    end

    def show
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        flash[:notice] = "文章建立成功"
        redirect_to posts_path
      else
        flash[:alert] = "此文章建立失敗，請檢查"
            render 'new'
      end
    end

    def edit
    end

    def update
      if @post.update(post_params)
        flash[:notice] = "文章修改成功"
        redirect_to posts_path
      else
        flash[:alert] = "此文章修改失敗，請檢查"
        render 'edit'
      end
    end

    def destroy
      @post.destroy
      flash[:notice] = "文章被刪除了"
      redirect_to posts_path
    end

    private

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :description, :image)
    end
  end

end

app/controllers/blog_controller.rb
class BlogController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/pages/about.html.erb
<% provide(:about_active, "active") %>
<h1>About Page</h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, "active") %>
<h1>Contact Page</h1>

app/views/blog/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:blog_active, "active") %>

<%= render "shared/form", post: @post %>

app/views/blog/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:blog_active, "active") %>

<div class="row">
	<%= render "shared/post" %>
	<%= link_to 'Create New Post', new_post_path %>
</div>

app/views/blog/posts/new.html.erb
<% provide(:page_title, "New Post") %>
<% provide(:blog_active, "active") %>

<%= render "shared/form", post: @post %>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, "active") %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.body %></p>
  </div>
  <%= link_to 'Back to index', posts_path %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container">
    <a class="navbar-brand" href="/">
      <span class="text-warning">Shela</span>blog
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Blog', root_path, class: "muted nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "muted nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: "muted nav-link #{yield(:contact_active)}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | ShelaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
  	<div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | ShelaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
  	<div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_for post do |f| %>

  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "errors") %> prohibitedthis post from being saved:</h2>
      <ul>
        <% post.errors_full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>

	<%= f.label :body, "Body" %>
	<%= f.text_field :body %>

	<%= f.label :description, "Description" %>
	<%= f.text_field :description %>

  <%= f.label :image, "Photo" %>
  <%= image_tag @post.image, width: '300px' if @post.image? %>
  <%= f.file_field :image %>

	<%= f.submit %>
<% end %>

app/views/shared/_post.html.erb
<% @posts.each do |post| %>
  <div class="col-sm-6 col-lg-4">

    <div class="card-deck" >
      <div class="card"  style="height: 450px;">
        <%= image_tag post.image, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= truncate(post.description, length: 150) %></p>
          <%= link_to '讀更多', post_path(post), class: "badge badge-primary" %>
        </div>
        <div class="card-footer">
          <small class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</small>
        </div>
      </div>
    </div>

  </div>
<% end %>